### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [j4mie/django-spurl#27]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.6.6. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary django-spurl -w /tmp/ext django-spurl==0.6.6
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting django-spurl==0.6.6
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/cae/c02d16e2ec46c/django-spurl-0.6.6.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-m0v2hhvf/django-spurl/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-m0v2hhvf/django-spurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-m0v2hhvf/django-spurl/pip-egg-info
         cwd: /tmp/pip-wheel-m0v2hhvf/django-spurl/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-m0v2hhvf/django-spurl/setup.py", line 39, in <module>
        long_description=read('README.rst') + '\n\n' + read('CHANGES.rst'),
      File "/tmp/pip-wheel-m0v2hhvf/django-spurl/setup.py", line 12, in read
        return codecs.open(file_path, encoding='utf-8').read()
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-m0v2hhvf/django-spurl/CHANGES.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
It appears this doesn't happen with current versions of setuptools/pip from the repo.

**Comment by bashu** [comment]
@thatch gonna release minor version

**Comment by bashu** [comment]
try django-spurl==0.6.7

```sh
$ pip3 wheel --no-binary django-spurl -w /tmp/ext django-spurl==0.6.7
Collecting django-spurl==0.6.7
  Downloading django-spurl-0.6.7.tar.gz (17 kB)
Processing /Users/bashu/Library/Caches/pip/wheels/6d/9f/65/f0e414e2ac1be3f726f12d3952e38a624629b1056d5fc76401/URLObject-2.4.3-py3-none-any.whl
  Saved /private/tmp/ext/URLObject-2.4.3-py3-none-any.whl
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Saved /private/tmp/ext/six-1.15.0-py2.py3-none-any.whl
Skipping urlobject, due to already being wheel.
Skipping six, due to already being wheel.
Building wheels for collected packages: django-spurl
  Building wheel for django-spurl (setup.py) ... done
  Created wheel for django-spurl: filename=django_spurl-0.6.7-py2.py3-none-any.whl size=13550 sha256=71900822d4289ef40cd8bfc9200a2cebe11b5958028052732a6c5bb27aa0fb58
  Stored in directory: /Users/bashu/Library/Caches/pip/wheels/17/c1/1d/d507ee5e59643e4ce490694e6d9168294c9b76959f415b90b3
Successfully built django-spurl
```
